# Mercedes-Benz Tech Innovation: Coding Task
# 
# Basic workflow that starts an Earthly build via GitHub Actions.
# Used to run JUnit tests in Earthly to be independent of GitHub-Actions,
# as Earthly could also be called from another CI such as Jenkins.
#
# Created with help from GitHub website and official Earthly docs.
name: CI-Build

# Control when the CI build will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allow to run workflow manually from Actions tab

# Steps to clone repository and execute tests via Earthly
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }}
    - name: Earthly installation
      uses: earthly/actions-setup@v1.0.7
      with:
        version: v0.7.11
        github-token: ${{ secrets.GH_TOKEN }}
    - name: Show Earthly version in console
      run: earthly --version
    - name: Put back the git branch into git (Earthly uses it for tagging)
      run: |
        branch=""
        if [ -n "$GITHUB_HEAD_REF" ]; then
          branch="$GITHUB_HEAD_REF"
        else
          branch="${GITHUB_REF##*/}"
        fi
        git checkout -b "$branch" || true
    - name: Execute all JUnit 5 tests
      run: earthly --ci +test
